name: Run Scheduled Function

on:
  schedule:
    - cron: '*/10 * * * *'  # This runs every 10 minutes

jobs:
  run-function:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run: |
        npm install  # If you have dependencies listed in package.json

    - name: Run fetch.js
      run: |
        node fetch.js
