name: Run Scheduled Function

on:
  schedule:
    - cron: '* * * * *'  # This runs every minute

jobs:
  run-function:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run: |
        npm init -y
        npm install node-fetch

    - name: Run fetch.js
      run: |
        node fetch.js